version: '3'

tasks:
  composer:
    desc: Выполнить composer install внутри контейнера php
    cmds:
      - docker compose exec php composer {{.CLI_ARGS}}

  console:
    desc: Выполнить любую Symfony-консольную команду в контейнере php
    cmds:
      - docker compose exec php php bin/console {{.CLI_ARGS}}
    interactive: true