version: '3'

tasks:
  start:
    desc: Развернуть проект
    cmds:
      - docker compose down
      - docker compose up -d --build
      - docker compose exec php composer install

  up:
    desc: Выполнить docker compose up
    cmds:
      - docker compose up {{.CLI_ARGS}}

  down:
    desc: Выполнить docker compose down
    cmds:
      - docker compose down

  composer:
    desc: Выполнить composer команду внутри контейнера php
    cmds:
      - docker compose exec php composer {{.CLI_ARGS}}

  console:
    desc: Выполнить любую Symfony-консольную команду в контейнере php
    cmds:
      - docker compose exec php php bin/console {{.CLI_ARGS}}
    interactive: true

  go:
    desc: Выполнить golang команду
    cmds:
      - docker compose run --rm go-cli go {{.CLI_ARGS}}
