version: '3'

tasks:
  start:
    desc: Развернуть проект
    cmds:
      - docker compose down
      - docker compose up -d --build --remove-orphans
      - docker compose exec php composer install

  up:
    desc: Выполнить docker compose up
    cmds:
      - docker compose up {{.CLI_ARGS}}

  down:
    desc: Выполнить docker compose down
    cmds:
      - docker compose down

  composer:
    desc: Выполнить composer команду внутри контейнера php
    cmds:
      - docker compose exec php composer {{.CLI_ARGS}}

  console:
    desc: Выполнить любую Symfony-консольную команду в контейнере php
    cmds:
      - docker compose exec php php bin/console {{.CLI_ARGS}}
    interactive: true

  codestyle:
    desc: Запустить php-cs-fixer внутри контейнера php и исправить стиль кода
    cmds:
      - docker compose exec php vendor/bin/php-cs-fixer fix

  go-send:
    desc: Отправить сообщение в kafka из Golang
    cmds:
      - docker compose run --rm golang_producer ./app

  go-read:
    desc: Прочитать сообщения из kafka в Golang
    cmds:
      - docker compose run --rm golang_consumer ./app

  php-send:
    desc: Отправить сообщение в kafka из symfony
    cmds:
      - docker compose exec php php bin/console app:send-kafka

  php-read:
    desc: Прочитать сообщения из kafka в symfony
    cmds:
      - docker compose exec php php bin/console messenger:consume kafka_test_topic -vv
